name: music_application
description: A Flutter music app
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:


  flutter:
    sdk: flutter


  provider: any
  intl: ^0.20.2
  uuid: ^4.4.0

  just_audio: any
  audio_session: ^0.2.2
  on_audio_query: ^2.9.0
  permission_handler: any
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


